# * Custom Prompt

format = """
[<m> ](bold #70d2ff)\
$aws\
$azure\
$gcloud\
$git_branch\
$git_commit\
$docker_context\
$python\
$golang\
$java\
$kotlin\
$nodejs\
$terraform\
$vagrant\
$package\
$kubernetes\
[</m>](bold #70d2ff)\n
[th3pl4gu3 ($directory) → ](bold #be90ff)
"""

[aws]
disabled = false
symbol = "☁️ "
style = "bold #ffcc67"

# [azure]
# disabled = false
# symbol = "☁️ "
# style = "bold #7fb7ff"

[gcloud]
disabled = false
format = '[G-$active \($project\)]($style) '
style = "bold yellow"

[directory]
style = "bold #ffca8d"

# Kubernetes module configuration
[kubernetes]
disabled = false
format = '☸ [$context( \($namespace\) )](bold cyan)'
symbol = ""
style = "bold cyan"
# detect_extensions = ["yaml", "yml", "json"]
# detect_files = ["kustomization.yaml", "kustomization.yml", "Chart.yaml"]
# detect_folders = ["kubernetes", "k8s", ".kube"]
